In [10]:
import numpy as np
def cal_weight(x,y):
    return np.dot(x.T,y)

def bipolar_function(matrix):
    return np.where(matrix>0,1,-1)

def forward(y,w):
    return bipolar_function(np.dot(y,w.T))

def backward(x,w):
    return bipolar_function(np.dot(x,w))
# define 2 pairs of vector
x= np.array([ [1,1,1,1,1,1],[-1,-1,-1,-1,-1,-1]])
y= np.array([[1,1,1],[-1,-1,-1]])

#calculate weight matrix
w = cal_weight(x,y)
print('weight matrix: \n',w)

#forward testing
print('forward testing:')
for i in range(len(y)):
    print(f'x{i+1}:',forward(y[i],w))

#backward testing
print('backward testing:')
for i in range(len(x)):
    print(f'y{i+1}:',backward(x[i],w))

weight matrix: 
 [[2 2 2]
 [2 2 2]
 [2 2 2]
 [2 2 2]
 [2 2 2]
 [2 2 2]]
forward testing:
x1: [1 1 1 1 1 1]
x2: [-1 -1 -1 -1 -1 -1]
backward testing:
y1: [1 1 1]
y2: [-1 -1 -1]
