In [2]:
import numpy as np

class ART:
    def __init__(self, rho):
        self.rho = rho      # Vigilance parameter
        self.clusters = []  # Stores learned patterns

    def match(self, x, w):
        return np.sum(np.minimum(x, w)) / np.sum(x) >= self.rho

    def train(self, data):
        for x in data:
            for i, w in enumerate(self.clusters):
                if self.match(x, w):
                    self.clusters[i] = np.minimum(w, x)
                    break
            else:
                self.clusters.append(x.copy())  # Create new cluster

    def predict(self, x):
        for i, w in enumerate(self.clusters):
            if self.match(x, w):
                return i
        return -1  # No matching cluster found

# Input patterns (training data)
patterns = np.array([
    [1, 0, 0, 0, 1, 0, 1],
    [0, 1, 0, 0, 0, 1, 1],
    [0, 0, 1, 0, 1, 1, 0],
    [0, 0, 0, 1, 0, 1, 1]
])

# Test patterns
tests = np.array([
    [1, 0, 0, 0, 1, 0, 1],
    [0, 1, 0, 0, 0, 1, 1],
    [0, 0, 1, 0, 1, 1, 0],
    [0, 0, 0, 1, 0, 1, 1],
    [1, 1, 0, 0, 0, 1, 0],
    [0, 0, 0, 0, 0, 0, 1]
])

# Create and train ART network
net = ART(rho=0.7)
net.train(patterns)

# Display results
print("Input Pattern\t\tMatched Cluster")
print("----------------------------------------")
for x in tests:
    print(f"{x}\tCluster {net.predict(x)}")


Input Pattern		Matched Cluster
----------------------------------------
[1 0 0 0 1 0 1]	Cluster 0
[0 1 0 0 0 1 1]	Cluster 1
[0 0 1 0 1 1 0]	Cluster 2
[0 0 0 1 0 1 1]	Cluster 3
[1 1 0 0 0 1 0]	Cluster -1
[0 0 0 0 0 0 1]	Cluster 0
